stages:
  - testflight

archive_project_testflight:
  stage: testflight
  script:
    - npm install
    - fastlane ios certificate
    - fastlane ios testflight
    # - fastlane android testflight
  only:
    - development
  tags:
    - ios
    - android